(define( domain babby-grid)
  (:requirements :equality)
  (:predicates
  (carry ?who ?what)
  (seat ?seat)
  (table ?where)
  (robot ?who)
  (white ?where)
  (black ?where)
  (closet ?where)
  (dishwasher ?where)
  (finished ?what)
  (washingmachine ?where)
  (clean ?what)
  (at ?who ?where)
  (tray ?what)
  (cloth ?what)
  (conn ?square-1 ?square-2)
  (loaded ?who)
  (clear ?where)
  )
  (:action move
    :parameters (?who ?from ?to)
    :precondition (and (robot ?who)
                        (white ?from)
                        (white ?to)
                        (at ?who ?from)
                        (conn ?from ?to)
                        )
    :effect (and (not(at ?who ?from))
                  (at ?who ?to)
                  )
  )
  (:action take-cloth-from-table
    :parameters (?who ?what ?where ?near ?seat-1 ?seat-2)
    :precondition (and (robot ?who)
                        (cloth ?what)
                        (table ?where)
                        (white ?near)
                        (seat ?seat-1)
                        (seat ?seat-2)
                        (not (= ?seat-1 ?seat-2))
                        (clear ?seat-1)
                        (clear ?seat-2)
                        (at ?who ?near)
                        (conn ?near ?where)
                        (at ?what ?where)
                        (not (loaded ?who))
                        )
    :effect (and (carry ?who ?what)
                  (loaded ?who)
                  (not (at ?what ?where))
                  (carry ?who ?what)
                  (clear ?where))
  )
  (:action take-tray-from-seat
    :parameters (?who ?what ?where ?near )
    :precondition (and (robot ?who)
                        (tray ?what)
                        (seat ?where)
                        (white ?near)
                        (conn ?near ?where)
                        (at ?who ?near)
                        (at ?what ?where)
                        (not (loaded ?who))
                        )
    :effect (and (loaded ?who)
                  (carry ?who ?what)
                  (not (at ?what ?where ))
                  (clear ?where)
                  )
  )
  (:action take-cloth-from-waschingmachine
    :parameters (?who ?what ?where ?near)
    :precondition (and (robot ?who)
                        (not (loaded ?who))
                        (cloth ?what)
                        (washingmachine ?where)
                        (white ?near)
                        (conn ?near ?where)
                        (at ?who ?near)
                        (at ?what ?where)
                        (finished ?where)
                        )
    :effect (and (loaded ?who)
                  (carry ?who ?what)
                  (not (at ?what ?where))
                  )
  )
  (:action take-tray-from-dishwasher
  :parameters (?who ?what ?where ?near)
  :precondition (and (robot ?who)
                      (not (loaded ?who))
                      (tray ?what)
                      (dishwasher ?where)
                      (white ?near)
                      (conn ?near ?where)
                      (at ?who ?near)
                      (at ?what ?where)
                      (finished ?where)
                      )
  :effect (and (loaded ?who)
                (carry ?who ?what)
                (not (at ?what ?where))
                )
)

  (:action run-washingmachine
    :parameters (?who ?what ?near ?inside)
    :precondition (and (robot ?who)
                        (washingmachine ?what)
                        (white ?near)
                        (conn ?near ?what)
                        (at ?who ?near)
                        (not (finished ?what))
                        (cloth ?inside)
                        (at ?inside ?what)
                  )
    :effect (and (finished ?what)
                  (clean ?inside))
  )
  (:action run-dishwasher
    :parameters (?who ?what ?near ?inside1 ?inside2)
    :precondition (and (robot ?who)
                        (dishwasher ?what)
                        (white ?near)
                        (conn ?near ?what)
                        (at ?who ?near)
                        (not (finished ?what))
                        (tray ?inside1)
                        (at ?inside1 ?what)
                        (tray ?inside2)
                        (at ?inside2 ?what)
                        (not (= ?inside1 ?inside2))
                  )
    :effect (and (finished ?what)
                  (clean ?inside1)
                  (clean ?inside2)
                  )
  )
  (:action put
    :parameters (?who ?what ?where ?near)
    :precondition (and (loaded ?who)
                        (carry ?who ?what)
                        (white ?near)
                        (at ?who ?near)
                        (conn ?near ?where)
                        )
    :effect (and (not (loaded ?who))
                  (not (carry ?who ?what))
                  (at ?what ?where)

                  )
)
)
