(define (domain vanilla-grid)
  (:requirements :strips)
  (:predicates
    (conn ?square-1 ?square-2)
    (ambush ?where)
    (black ?square)
    (white ?square)
    (at ?who ?where )
    (place ?where ))
  (:action move
    :parameters (?who ?from ?to ?ambusher ?intermediate)
    :precondition (and (at ?who ?from)
                  (place ?from)
                  (place ?to)
                  (conn ?from ?to)
                  (conn ?to ?intermediate)
                  (not (ambush ?intermediate))
                  (not (black ?to)))
    :effect (and (at ?who ?to)
              (not( at ?who ?from)))
    )
)
