(define (domain vanilla-grid)
  (:requirements :strips)
  (:predicates
    (conn ?square-1 ?square-2)
    (black ?square)
    (white ?square)
    (at ?who ?where )
    (robot ?who)
    )
  (:action move
    :parameters (?who ?from ?to)
    :precondition (and (at ?who ?from)
                        (conn ?from ?to)
                        (white ?from)
                        (not (black ?to)))
    :effect (and (at ?who ?to)
                (not( at ?who ?from)))
    )
)
